<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 3.0.3 (doctrine2-annotation) on 2017-03-08 20:58:04.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * Entity\Usuario
 *
 * @ORM\Entity(repositoryClass="UsuarioRepository")
 * @ORM\Table(name="usuario")
 */
class Usuario
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(type="string", length=45, nullable=true)
     */
    protected $nombre;

    /**
     * @ORM\Column(type="string", length=45, nullable=true)
     */
    protected $apellidos;

    /**
     * @ORM\Column(type="string", length=45, nullable=true)
     */
    protected $documento;

    /**
     * @ORM\Column(type="string", length=45, nullable=true)
     */
    protected $email;

    /**
     * @ORM\Column(type="string", length=45, nullable=true)
     */
    protected $telefono;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    protected $pais;

    /**
     * @ORM\OneToMany(targetEntity="Agenda", mappedBy="usuario")
     * @ORM\JoinColumn(name="id", referencedColumnName="usuario_id", nullable=false)
     */
    protected $agendas;

    public function __construct()
    {
        $this->agendas = new ArrayCollection();
    }

    /**
     * Set the value of id.
     *
     * @param integer $id
     * @return \Entity\Usuario
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Get the value of id.
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set the value of nombre.
     *
     * @param string $nombre
     * @return \Entity\Usuario
     */
    public function setNombre($nombre)
    {
        $this->nombre = $nombre;

        return $this;
    }

    /**
     * Get the value of nombre.
     *
     * @return string
     */
    public function getNombre()
    {
        return $this->nombre;
    }

    /**
     * Set the value of apellidos.
     *
     * @param string $apellidos
     * @return \Entity\Usuario
     */
    public function setApellidos($apellidos)
    {
        $this->apellidos = $apellidos;

        return $this;
    }

    /**
     * Get the value of apellidos.
     *
     * @return string
     */
    public function getApellidos()
    {
        return $this->apellidos;
    }

    /**
     * Set the value of documento.
     *
     * @param string $documento
     * @return \Entity\Usuario
     */
    public function setDocumento($documento)
    {
        $this->documento = $documento;

        return $this;
    }

    /**
     * Get the value of documento.
     *
     * @return string
     */
    public function getDocumento()
    {
        return $this->documento;
    }

    /**
     * Set the value of email.
     *
     * @param string $email
     * @return \Entity\Usuario
     */
    public function setEmail($email)
    {
        $this->email = $email;

        return $this;
    }

    /**
     * Get the value of email.
     *
     * @return string
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * Set the value of telefono.
     *
     * @param string $telefono
     * @return \Entity\Usuario
     */
    public function setTelefono($telefono)
    {
        $this->telefono = $telefono;

        return $this;
    }

    /**
     * Get the value of telefono.
     *
     * @return string
     */
    public function getTelefono()
    {
        return $this->telefono;
    }

    /**
     * Set the value of pais.
     *
     * @param integer $pais
     * @return \Entity\Usuario
     */
    public function setPais($pais)
    {
        $this->pais = $pais;

        return $this;
    }

    /**
     * Get the value of pais.
     *
     * @return integer
     */
    public function getPais()
    {
        return $this->pais;
    }

    /**
     * Add Agenda entity to collection (one to many).
     *
     * @param \Entity\Agenda $agenda
     * @return \Entity\Usuario
     */
    public function addAgenda(Agenda $agenda)
    {
        $this->agendas[] = $agenda;

        return $this;
    }

    /**
     * Remove Agenda entity from collection (one to many).
     *
     * @param \Entity\Agenda $agenda
     * @return \Entity\Usuario
     */
    public function removeAgenda(Agenda $agenda)
    {
        $this->agendas->removeElement($agenda);

        return $this;
    }

    /**
     * Get Agenda entity collection (one to many).
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getAgendas()
    {
        return $this->agendas;
    }

    public function __sleep()
    {
        return array('id', 'nombre', 'apellidos', 'documento', 'email', 'telefono', 'pais');
    }
}